version: "3"
services:
  web:
    build:
      context: ./
      target: setup
    command: sleep infinity
    depends_on:
      - db
    volumes:
      - .:/workspaces/orcasound-next
      - ../orcasite:/workspaces/orcasite
      - ../../postoccupancy/esp32_ui:/workspaces/esp32_ui
      - ../../postoccupancy/esp32_api:/workspaces/esp32_api

